name: news_times
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.3
  dio: ^5.4.1
  shared_preferences: ^2.2.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_rating_bar: ^4.0.1
  internet_connection_checker_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - .env

